services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/loginform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: loginform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
